-- CMS v3 Upgrade Migration
-- Created at: 2026-02-20
-- Adds: Authors, Post Categories, Site Settings, expanded post/tool fields

-- ══════════════════════════════════════════════════════════════════════════════
-- 1. AUTHORS TABLE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS authors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  bio TEXT DEFAULT '',
  headshot_url TEXT,
  expertise_areas JSONB DEFAULT '[]'::jsonb,
  social_profiles JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE authors ENABLE ROW LEVEL SECURITY;

-- Public can read authors
CREATE POLICY "authors_public_read" ON authors
  FOR SELECT USING (true);

-- Editors+ can manage authors
CREATE POLICY "authors_admin_insert" ON authors
  FOR INSERT WITH CHECK (
    public.get_user_role() IN ('super_admin', 'manager', 'editor')
  );

CREATE POLICY "authors_admin_update" ON authors
  FOR UPDATE USING (
    public.get_user_role() IN ('super_admin', 'manager', 'editor')
  );

CREATE POLICY "authors_admin_delete" ON authors
  FOR DELETE USING (
    public.get_user_role() = 'super_admin'
  );

GRANT SELECT ON authors TO anon;

-- ══════════════════════════════════════════════════════════════════════════════
-- 2. POST CATEGORIES JUNCTION TABLE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS post_categories (
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, category_id)
);

ALTER TABLE post_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "post_categories_public_read" ON post_categories
  FOR SELECT USING (true);

CREATE POLICY "post_categories_admin_insert" ON post_categories
  FOR INSERT WITH CHECK (
    public.get_user_role() IN ('super_admin', 'manager', 'editor')
  );

CREATE POLICY "post_categories_admin_delete" ON post_categories
  FOR DELETE USING (
    public.get_user_role() IN ('super_admin', 'manager', 'editor')
  );

GRANT SELECT ON post_categories TO anon;

-- ══════════════════════════════════════════════════════════════════════════════
-- 3. SITE SETTINGS TABLE (single-row)
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_name TEXT DEFAULT 'ToolStack',
  site_tagline TEXT DEFAULT 'Discover the Best SaaS Tools',
  logo_url TEXT,
  favicon_url TEXT,
  default_meta_title TEXT DEFAULT 'ToolStack — Discover the Best SaaS Tools',
  default_meta_description TEXT DEFAULT 'Curated SaaS tool reviews, comparisons, and recommendations.',
  default_og_image TEXT,
  featured_tool_slugs JSONB DEFAULT '[]'::jsonb,
  featured_post_slugs JSONB DEFAULT '[]'::jsonb,
  social_links JSONB DEFAULT '{}'::jsonb,
  custom_scripts JSONB DEFAULT '{}'::jsonb,
  ftc_disclosure TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- Public read for site settings
CREATE POLICY "settings_public_read" ON site_settings
  FOR SELECT USING (true);

-- Only super_admin can update settings
CREATE POLICY "settings_admin_update" ON site_settings
  FOR UPDATE USING (
    public.get_user_role() = 'super_admin'
  );

GRANT SELECT ON site_settings TO anon;

-- Insert default row
INSERT INTO site_settings (id, site_name)
VALUES (1, 'ToolStack')
ON CONFLICT (id) DO NOTHING;

-- ══════════════════════════════════════════════════════════════════════════════
-- 4. EXPAND POSTS TABLE
-- ══════════════════════════════════════════════════════════════════════════════

ALTER TABLE posts
ADD COLUMN IF NOT EXISTS author_id BIGINT REFERENCES authors(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS faq_items JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS primary_keyword TEXT,
ADD COLUMN IF NOT EXISTS secondary_keywords JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS search_intent TEXT DEFAULT 'informational',
ADD COLUMN IF NOT EXISTS show_in_nav BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS nav_label TEXT,
ADD COLUMN IF NOT EXISTS nav_position INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS publish_date TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS blog_type TEXT DEFAULT 'standard',
ADD COLUMN IF NOT EXISTS featured_image_alt TEXT DEFAULT '';

-- ══════════════════════════════════════════════════════════════════════════════
-- 5. EXPAND POST_TOOLS TABLE (editorial enrichment)
-- ══════════════════════════════════════════════════════════════════════════════

ALTER TABLE post_tools
ADD COLUMN IF NOT EXISTS caption TEXT,
ADD COLUMN IF NOT EXISTS short_editorial TEXT,
ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS pros JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS cons JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS who_its_for TEXT,
ADD COLUMN IF NOT EXISTS verdict_badge TEXT,
ADD COLUMN IF NOT EXISTS testing_notes TEXT;

-- ══════════════════════════════════════════════════════════════════════════════
-- 6. ADD MISSING updated_at TO TOOLS TABLE
-- ══════════════════════════════════════════════════════════════════════════════

ALTER TABLE tools
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- Auto-update updated_at trigger for tools
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Tools trigger
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'tools_updated_at'
  ) THEN
    CREATE TRIGGER tools_updated_at
      BEFORE UPDATE ON tools
      FOR EACH ROW
      EXECUTE FUNCTION update_updated_at_column();
  END IF;
END;
$$;

-- Authors trigger
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'authors_updated_at'
  ) THEN
    CREATE TRIGGER authors_updated_at
      BEFORE UPDATE ON authors
      FOR EACH ROW
      EXECUTE FUNCTION update_updated_at_column();
  END IF;
END;
$$;

-- Site settings trigger
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'site_settings_updated_at'
  ) THEN
    CREATE TRIGGER site_settings_updated_at
      BEFORE UPDATE ON site_settings
      FOR EACH ROW
      EXECUTE FUNCTION update_updated_at_column();
  END IF;
END;
$$;

-- ══════════════════════════════════════════════════════════════════════════════
-- 7. INDEXES FOR PERFORMANCE
-- ══════════════════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_authors_slug ON authors(slug);
CREATE INDEX IF NOT EXISTS idx_posts_author_id ON posts(author_id);
CREATE INDEX IF NOT EXISTS idx_posts_search_intent ON posts(search_intent);
CREATE INDEX IF NOT EXISTS idx_posts_show_in_nav ON posts(show_in_nav) WHERE show_in_nav = true;
CREATE INDEX IF NOT EXISTS idx_post_categories_post ON post_categories(post_id);
CREATE INDEX IF NOT EXISTS idx_post_categories_cat ON post_categories(category_id);
