-- CMS v2 & Ledger System Migration
-- Created at: 2026-02-13

-- ══════════════════════════════════════════════════════════════════════════════
-- 1. ENUMS & TYPES
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TYPE user_role_type AS ENUM ('super_admin', 'manager', 'editor', 'reviewer', 'data_entry');
CREATE TYPE content_status AS ENUM ('draft', 'needs_review', 'approved', 'scheduled', 'published', 'archived');
CREATE TYPE content_entity_type AS ENUM ('tool', 'post');
CREATE TYPE ledger_account_type AS ENUM ('affiliate_network', 'internal', 'manual');
CREATE TYPE ledger_entry_type AS ENUM ('commission', 'adjustment', 'payout');
CREATE TYPE payout_status AS ENUM ('pending', 'completed', 'failed');

-- ══════════════════════════════════════════════════════════════════════════════
-- 2. RBAC & USERS
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS user_roles (
  user_id UUID REFERENCES auth.users(id) NOT NULL PRIMARY KEY,
  role user_role_type NOT NULL DEFAULT 'data_entry',
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;

-- ══════════════════════════════════════════════════════════════════════════════
-- 3. CORE CONTENT UPGRADES (Tools & Posts)
-- ══════════════════════════════════════════════════════════════════════════════

-- Add Workflow & SEO columns to TOOLS
ALTER TABLE tools 
ADD COLUMN IF NOT EXISTS status content_status DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS meta_title TEXT,
ADD COLUMN IF NOT EXISTS meta_description TEXT,
ADD COLUMN IF NOT EXISTS canonical_url TEXT,
ADD COLUMN IF NOT EXISTS og_image TEXT,
ADD COLUMN IF NOT EXISTS is_indexed BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS submitted_by UUID REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;

-- Migrate existing 'published' boolean to 'status' enum
UPDATE tools SET status = 'published' WHERE published = true;
UPDATE tools SET status = 'draft' WHERE published = false;

-- Add Workflow & SEO columns to POSTS
ALTER TABLE posts
ADD COLUMN IF NOT EXISTS status content_status DEFAULT 'draft',
ADD COLUMN IF NOT EXISTS meta_title TEXT,
ADD COLUMN IF NOT EXISTS meta_description TEXT,
ADD COLUMN IF NOT EXISTS canonical_url TEXT,
ADD COLUMN IF NOT EXISTS og_image TEXT,
ADD COLUMN IF NOT EXISTS is_indexed BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS submitted_by UUID REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS approved_by UUID REFERENCES auth.users(id),
ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;

-- Migrate existing 'published' boolean to 'status' enum
UPDATE posts SET status = 'published' WHERE published = true;
UPDATE posts SET status = 'draft' WHERE published = false;

-- ══════════════════════════════════════════════════════════════════════════════
-- 4. CMS SUPPORT TABLES
-- ══════════════════════════════════════════════════════════════════════════════

-- Content Versions (History)
CREATE TABLE IF NOT EXISTS content_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type content_entity_type NOT NULL,
  entity_id BIGINT NOT NULL,
  version_data JSONB NOT NULL,
  edited_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Tags
CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Tool Tags Junction
CREATE TABLE IF NOT EXISTS tool_tags (
  tool_id BIGINT REFERENCES tools(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (tool_id, tag_id)
);

-- Media Assets
CREATE TABLE IF NOT EXISTS media_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_path TEXT NOT NULL,
  alt_text TEXT,
  width INTEGER,
  height INTEGER,
  size_bytes BIGINT,
  mime_type TEXT,
  uploaded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Comments (Internal Workflow)
CREATE TABLE IF NOT EXISTS content_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type content_entity_type NOT NULL,
  entity_id BIGINT NOT NULL,
  comment TEXT NOT NULL,
  created_by UUID REFERENCES auth.users(id),
  resolved BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Scheduled Jobs
CREATE TABLE IF NOT EXISTS scheduled_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type content_entity_type NOT NULL,
  entity_id BIGINT NOT NULL,
  publish_at TIMESTAMPTZ NOT NULL,
  status TEXT DEFAULT 'pending', -- pending, completed, failed
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ══════════════════════════════════════════════════════════════════════════════
-- 5. LEDGER SYSTEM (Affiliate Finance)
-- ══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS ledger_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  account_type ledger_account_type NOT NULL,
  contact_email TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payout_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT REFERENCES ledger_accounts(id) NOT NULL,
  total_amount NUMERIC(12, 2) NOT NULL,
  currency TEXT DEFAULT 'USD',
  payout_date TIMESTAMPTZ,
  status payout_status DEFAULT 'pending',
  transaction_ref TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT REFERENCES ledger_accounts(id) NOT NULL,
  tool_id BIGINT REFERENCES tools(id),
  amount NUMERIC(12, 2) NOT NULL,
  currency TEXT DEFAULT 'USD',
  entry_type ledger_entry_type NOT NULL,
  reference_id TEXT, -- e.g., Invoice ID, Transaction ID
  notes TEXT,
  payout_id BIGINT REFERENCES payout_records(id), -- Null means unpaid
  occurred_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ══════════════════════════════════════════════════════════════════════════════
-- 6. ENABLE RLS
-- ══════════════════════════════════════════════════════════════════════════════

ALTER TABLE content_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE tool_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE media_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE payout_records ENABLE ROW LEVEL SECURITY;

-- ══════════════════════════════════════════════════════════════════════════════
-- 7. RLS POLICIES
-- ══════════════════════════════════════════════════════════════════════════════

-- Helper: Check basic role existence
CREATE OR REPLACE FUNCTION public.has_role(required_role user_role_type)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid()
    AND role = required_role
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper: Check admin hierarchy (Super Admin > Manager > Editor > Reviewer > Data Entry)
CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS user_role_type AS $$
BEGIN
  RETURN (SELECT role FROM public.user_roles WHERE user_id = auth.uid() LIMIT 1);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7.1 USER ROLES POLICIES
-- Only Super Admins can manage roles
CREATE POLICY "Super Admins manage roles" ON user_roles
  USING (has_role('super_admin'));
  
-- Users can read their own role (or admins can read all)
CREATE POLICY "Read own role" ON user_roles FOR SELECT
  USING (auth.uid() = user_id OR has_role('super_admin'));

-- 7.2 CONTENT POLICIES (Tools, Posts)
-- Everyone read published (handled by existing policies usually, but reinforcing)
-- Editors+ can create/update
-- Only Managers+ can publish
-- Only Super Admins can delete

-- 7.3 LEDGER POLICIES
-- View: Managers & Super Admins
CREATE POLICY "Admins view ledger" ON ledger_entries FOR SELECT
  USING (has_role('super_admin') OR has_role('manager'));

-- Insert: System / Managers
CREATE POLICY "Managers add ledger entries" ON ledger_entries FOR INSERT
  WITH CHECK (has_role('super_admin') OR has_role('manager'));

-- Update: Block if payout_id is set (Immutable after payout)
CREATE POLICY "Modify unpaid ledger entries" ON ledger_entries FOR UPDATE
  USING ((has_role('super_admin') OR has_role('manager')) AND payout_id IS NULL)
  WITH CHECK (payout_id IS NULL);  -- Prevent attaching to payout via easy update? (Need separate Payout flow)

-- Delete: ONLY Super Admin
CREATE POLICY "Super Admin delete ledger" ON ledger_entries FOR DELETE
  USING (has_role('super_admin'));

